# Generated by Django 5.0.1 on 2024-01-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
    ]
